/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelmagic.GUI;

import java.awt.Color;
import java.awt.Graphics;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import travelmagic.map.AttractionLabel;
import travelmagic.map.HotelLabel;
import travelmagic.map.mapProcessor;
import travelmagic.objects.Attraction;
import travelmagic.objects.Hotel;
import travelmagic.objects.RouteProcessor;
import travelmagic.objects.TravelSystem;

/**
 *
 * @author Yijun
 */
public class userMainGUI extends javax.swing.JFrame {

    private RouteProcessor RouteProcessor;
    private mapProcessor mapProcessor;
    LinkedList<Attraction> aList = TravelSystem.getAttractions();
    LinkedList<Hotel> hList = TravelSystem.getHotels();
    int xDistance;
    int yDistance;
    LinkedList<Attraction> plan = new LinkedList<Attraction>();

    /**
     * Creates new form userMainGUI
     */
    public userMainGUI() {

        initComponents();
        jPanel1.removeAll();
        for (Attraction a : aList) {
            AttractionLabel attractionLabel = new AttractionLabel();
            attractionLabel.validate();
            attractionLabel.setLocation(a.getCoordinate().getX(), a.getCoordinate().getY());
            attractionLabel.setSize(10, 10);
            jPanel1.add(attractionLabel);
            SwingUtilities.updateComponentTreeUI(attractionLabel);
        }
        for (Hotel h : hList) {
            HotelLabel hotelLabel = new HotelLabel();
            hotelLabel.validate();
            hotelLabel.setLocation(h.getCoordinate().getX(), h.getCoordinate().getY());
            hotelLabel.setSize(10, 10);
            jPanel1.add(hotelLabel);
            SwingUtilities.updateComponentTreeUI(hotelLabel);
        }
        JLabel j = new JLabel();
        j.setLayout(null);
        j.setSize(377, 403);
        Icon icon = new ImageIcon("map.jpg");
        j.setIcon(icon);
        jPanel1.add(j);
        mapProcessor = new mapProcessor(/*"C:\\Users\\Yijun\\Desktop\\map.jpg"*/"map.jpg", jPanel2.getWidth(), jPanel2.getHeight(), jSlider1.getValue());
        //DefaultListModel m1 = (DefaultListModel)(attractionsPerferences.getModel());
        //m1.clear();
        //for(Hotel h:hList){m1.addElement(h.toString());
        //attractionsPerferences.addElement();
        DefaultComboBoxModel model = (DefaultComboBoxModel) (attractionsPerferences.getModel());
        model.addElement("No special perference");
        for (int i = 0; i < aList.size(); i++) {
            if (model.getIndexOf(aList.get(i).getType()) == -1) {
                model.addElement(aList.get(i).getType());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startLocationText = new javax.swing.JTextField();
        destinationText = new javax.swing.JTextField();
        attractionsPerferences = new javax.swing.JComboBox();
        routePerferences = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        budgetText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        modifyButton = new javax.swing.JButton();
        outputButton = new javax.swing.JButton();
        generateButton = new javax.swing.JButton();
        searchText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        reservationMenu = new javax.swing.JMenu();
        travelingCautionsMenu = new javax.swing.JMenu();

        jLabel6.setText("Cautions and Tips");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\nAlways pack a hat. In the winter, a knit hat will keep you warm and take up little room. In the summer, a brimmed hat will keep the sun off your face. In either case, it will save you when your straightening iron doesn¡¯t work in the trapezoidal electrical socket you found in your hotel room.\n-\nPacking for a trip is infinitely easier when you¡¯ve just done laundry.\n-\nBring a travel first aid kit with the following: ibuprofen (or other pain killer), decongestant, NyQuil, bandages, hydrocortizone cream. You will not believe how often it will come in handy.\n-\nGoing somewhere with clean drinking water? Pack a reusable water bottle that clips on to your bag. Bonus points if it¡¯s collapsible. In an age where the bottled stuff costs $7, you¡¯ll save a ton, too.\n-\nYou will never wear that second dressy outfit, so stop packing it. Most trips, you won¡¯t even wear the first dressy outfit (but you should still pack that one).\n-\nBags with wheels are amazing. That backpack might seem more agile, but have you ever seen someone trek across an airport with one of those on their back? Nimble does not come to mind. Sciatica, yes. But not nimble.\n-\nDon¡¯t forget your camera charger. You will go through that battery in a second, esp. when your friends insist on flipping through all of the photos that you just took in order to relive something that happened 5 minutes ago.\n-\nDon¡¯t pack clothes that require ironing. Hell, don¡¯t buy clothes that require ironing.\n-\nIf you are staying with someone, get them a present. Either bring it from home, or take them out during the trip, or send them something afterwards. Do it not only because you will likely be invited back, but because your mom will be so proud.\n-\nNever pack something that you haven¡¯t worn before. Otherwise you¡¯ll find your new shoes too uncomfortable, your new jacket too flimsy, your new underwear too wedgie-prone.\n-\nBuy that delightfully grotesque souvenir, even if you don¡¯t know who to give it to. Odds are, you will think of someone for whom it would be perfect. Worst-case scenario, you¡¯ll keep it for yourself. Which is a really great worst-case scenario.\n\nI really should have bought one of those ridiculous hats. Because you can never have enough.\n-\n\nIf you hate wearing something at home, you will hate wearing it even more on a trip.\n-\nPack those god-awful tennis shoes you only wear ¡°jogging¡± (a.k.a., ¡°to the store to buy ice cream¡±) At some point during your trip, you won¡¯t care what you look like. You will only care about being comfortable. For me, that point is ¡°Day 2.¡±\n-\nDo not go into a McDonald¡¯s. I don¡¯t care if you are scared and starving ? McNuggets are NEVER a viable option. If you need fast food, at least hit up a regional chain.\n\nOr consider picking a restaurant based on its name alone.\n-\n\nAlways ask museum staff for tips. They¡¯ll tell you what the best exhibits are, and what you can skip.\n\nPlus, they probably get bored looking at naked bodies all day and are DYING for a little human interaction.\n-\n\nIf you are at an aquarium or a planetarium, feel free to skip the IMAX movie. They cost a bundle, and are the same EVERYWHERE.\n-\nTip your hotel housekeeping staff. (A good rule is to leave them about $2 U.S./day.) While you can leave it every day on the pillow, most staff is instructed not to move money or personal items, so they might not pick it up. If this is the case, just leave it in a prominent spot when you check out.\n-\nNever carry your wallet in your back pocket, and never carry your purse on just your shoulder.\n-\nTake notes. As much as you believe the contrary, once you get home you will not remember your tour guide¡¯s name, or the artist whose worked you loved so much, or even the city where you stayed. Write it down.\n-\nIf you have an inkling that you should be taking photos of something, take them.\n- \nIf you have an inkling that you should not be taking photos of something, don¡¯t take them.\n- \nThe second you think of packing something, PACK IT. If you wait, you will forget. And then you¡¯ll end up using a plastic bag as a shower cap. Subsequent attempts to seduce your husband will be impossible after he¡¯s seen you with a Rite-Aid sack on your head.\n- \nIf you don¡¯t speak the local language of the place you are heading, then at least learn the following phrases: Please. Thank you. I¡¯m sorry. Do you have those shoes in a size 37?\n-\nWherever you  are, wherever you are going, bring snacks.\n- \nDry shampoo is a godsend for those days when you don¡¯t have time to wash your hair, but still want to interact with other humans.\n-\nYou will inevitably forget something, either at home or while on your trip. Accept this reality, and pray it is not your passport or your spouse.\n- \nCall your credit card company before you leave and put a travel alert on your card. While you¡¯re at it, jot down their international customer service number.\n-\nConsider contacting the embassy and letting them know the dates of your trip. Or at the very least, have their contact info on hand.\n-\nMake photocopies of your passport and leave one with friends and another tucked into your bag. Or, better yet, scan your passport and email a copy to yourself.\n-\nPack more underwear than you could ever conceivably go through. They don¡¯t take up much room, and after a few days on the road, you will feel FRIGGING DECADENT when you put on a fresh pair in the morning and again in the afternoon.\n-\nStuffing socks into your shoes can help you save space and ensure your loafers retain their shape.\n-\nNo one will judge you for watching a dumb movie while on a plane. That¡¯s what you¡¯re supposed to do on planes.\n-\nWhen packing, try to match all of the pants/bottoms you are taking with all of the tops. This will prevent you from looking like a total goober by the end of your trip.\n\nThough sometimes you will look like a goober anyway, because you really can't dress yourself.\n-\n\nDryer sheets remove static from your hair and clothing and make your suitcase smell awesome while taking up virtually no room.\n-\nDo not, under ANY circumstances, use an airplane lavatory while not wearing shoes. That is not okay. I don¡¯t care how swollen your feet are. Also, consider rolling up the hems of your pants while you are in there, so they don¡¯t brush the floor.\n-\nToilet paper is not a given in many parts of the world. Which is why those little packs of tissues they sell at drugstores are a godsend.\n-\nIt is far easier to get drunk and make an ass of yourself at 30,000 feet than when you are on the ground.\n\nOf course, that doesn't mean it's difficult to get drunk on the ground. Just MORE difficult than on a plane.\n-\n\nBorder control agents do not get sarcasm.\n- \nIf you can¡¯t afford to lose it (either financially or emotionally), don¡¯t pack it.\n- \nWhen in Bulgaria, never get into a cab that doesn¡¯t have a meter.\n- \nIf you¡¯ve selected the window seat, you¡¯d better have a big bladder.\n-\nIf you are starting a brand-new book on your flight, bring at least one other form of entertainment with you, because that brand-new book might suck.\n- \nSuffer from motion sickness? Ask for a drink that is half ginger ale and half club soda. It will help alleviate nausea without putting you into diabetic shock.\n-\nNever check any of the following: your toothbrush, your prescription medications, your deodorant, your pjs.\n-\nWear sunscreen anytime you will be outside, regardless of the temperature or weather.\n-\nRegardless of size, never bring more than two bags with you- any more than that is unwieldy and difficult to keep track of.\n\nThis poor gal was more pack mule than human. But she did have the legs of a 25-year-old, so there's that.\n-\n\nRolling non-wrinkable items before shoving them into your suitcase really does save space.\n-\nA passport protector is the most useless item anyone can buy, ever.\n-\nIf you¡¯ve forgotten something, check with the hotel before running to a drugstore. Most housekeeping departments carry toothbrushes, combs, sewing kits, shower caps, and disposable razors that they will give you free of charge.\n\nBonus! If you get a teeny tiny tube of toothpaste, you can pretend you are a giant.\n-\n\nBudget hotels almost always offer free wi-fi. Luxury hotels will charge you for it. This is almost always the case.\n-\nSleeping in while traveling is only acceptable if there is absolutely NOTHING better to do. In other words, it¡¯s never acceptable.\n- \nNever trust a theater review from a London critic.\n- \nDon¡¯t take foreign guests to an Americanized version of their cuisine. I know I shouldn¡¯t generalize, but NO ITALIAN HAS EVER WANTED TO GO TO THE OLIVE GARDEN.\n-\nIf a restaurants posts its menu in more than three languages, the food is probably going to suck.\n- \nAnd, most importantly: never, EVER leave any valuables in your vehicle. I don¡¯t care if it¡¯s safely hidden in the trunk. I don¡¯t care if you¡¯re parked in the safest part of town. Don¡¯t do it. It¡¯s not worth the risk.");
        jScrollPane3.setViewportView(jTextArea1);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel6))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Starting location");

        jLabel2.setText("Destination");

        routePerferences.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No special route Perference", "Lowest price route", "Least days route" }));

        jLabel3.setText("Budget");

        jList1.setModel(new javax.swing.DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("Route/Attraction/Hotel Information");

        jLabel5.setText("Plan information");

        jList2.setModel(new javax.swing.DefaultListModel());
        jScrollPane2.setViewportView(jList2);

        modifyButton.setText("Remove from plan");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        outputButton.setText("Output");
        outputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputButtonActionPerformed(evt);
            }
        });

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        searchText.setText("Enter place here");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        /*jPanel1.setLocation(0,0);
        jPanel1.setSize(377,403);
        JLabel j=new JLabel();
        j.setLayout(null);
        j.setSize(377,403);
        Icon icon=new ImageIcon("C:\\Users\\Yijun\\Desktop\\map.jpg");
        j.setIcon(icon);
        jPanel1.add(j);*/
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        reservationMenu.setText("Hotel Reservation");
        reservationMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(reservationMenu);

        travelingCautionsMenu.setText("Traveling Cautions/Tips");
        travelingCautionsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                travelingCautionsMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(travelingCautionsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(searchText, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(destinationText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(startLocationText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(budgetText))
                            .addComponent(attractionsPerferences, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(routePerferences, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addComponent(outputButton)
                            .addComponent(modifyButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(generateButton)
                        .addGap(325, 325, 325)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(startLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(destinationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(attractionsPerferences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(routePerferences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(budgetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addComponent(generateButton)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modifyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchButton))
                                .addGap(20, 20, 20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(outputButton)
                                .addGap(49, 49, 49))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if (evt.getClickCount() == 2) {
            mapProcessor.adjustShowCenter(evt.getX(), evt.getY());
            ImageIcon Icon = mapProcessor.adjustScale(jSlider1.getValue());
            jPanel2.setSize(241, 194);
            jPanel2.removeAll();
            JLabel jl = new JLabel();
            jl.setLayout(null);
            jl.setLocation(0, 0);
            jl.setSize(241, 194);
            jl.setIcon(Icon);
            jPanel2.add(jl);
            SwingUtilities.updateComponentTreeUI(jl);
        } else if (evt.getButton() == evt.BUTTON3) {
            DefaultListModel m1 = (DefaultListModel) (jList1.getModel());
            m1.clear();
            for (int i = 0; i < aList.size(); i++) {
                xDistance = Math.abs(evt.getX() - aList.get(i).getCoordinate().getX());
                yDistance = Math.abs(evt.getY() - aList.get(i).getCoordinate().getY());
                if ((xDistance < 10) && (yDistance < 10)) {
                    m1.addElement(aList.get(i).toString());
                }
            }
            for (int i = 0; i < hList.size(); i++) {
                xDistance = Math.abs(evt.getX() - hList.get(i).getCoordinate().getX());
                yDistance = Math.abs(evt.getY() - hList.get(i).getCoordinate().getY());
                if ((xDistance < 10) && (yDistance < 10)) {
                    m1.addElement(hList.get(i).toString());
                }
            }
        }

    }//GEN-LAST:event_jPanel1MouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        DefaultListModel m1 = (DefaultListModel) (jList1.getModel());
        m1.clear();
        for (int i = 0; i < aList.size(); i++) {
            if (searchText.getText().equals(aList.get(i).getName())) {
                m1.addElement(aList.get(i).toString());
            }
        }
        for (int i = 0; i < hList.size(); i++) {
            if (searchText.getText().equals(hList.get(i).getName())) {
                m1.addElement(hList.get(i).toString());
            }
        }
        if (m1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, cannot find the place you are looking for.");
        }// TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void travelingCautionsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_travelingCautionsMenuMouseClicked
        jDialog1.setSize(400, 600);
        jDialog1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_travelingCautionsMenuMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialog1.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new MainForm().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void reservationMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationMenuMouseClicked
        new userReservationGUI().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationMenuMouseClicked

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        //LinkedList<Attraction> plan;
        RouteProcessor = new RouteProcessor();
        DefaultListModel m2 = (DefaultListModel) (jList2.getModel());
        m2.clear();
        DefaultListModel m1 = (DefaultListModel) (jList1.getModel());
        m1.clear();
        String planAttractions = "Route is:";
        Double planBudget = 0.0;
        int planDays = 0;
        String weather = "Weather will be:";
        if (((startLocationText.getText()).length() < 1) || ((destinationText.getText()).length() < 1)) {
            JOptionPane.showMessageDialog(null, "Sorry, please fill in both start location and destination.");
        } else {
            if (budgetText.getText().length() < 1) {
                RouteProcessor.setBudget(9999999);
            } else {
                RouteProcessor.setBudget(Double.parseDouble(budgetText.getText()));
            }
            for (Attraction a : aList) {
                if ((a.getName()).equals(destinationText.getText())) {
                    RouteProcessor.setDestination(a);
                    break;
                }
            }
            for (Attraction a : aList) {
                if ((a.getName()).equals(startLocationText.getText())) {
                    RouteProcessor.setStart(a);
                    break;
                }
            }
            RouteProcessor.setAttractionPerference(attractionsPerferences.getSelectedItem().toString());

            if (routePerferences.getSelectedIndex() == 1) {
                plan = RouteProcessor.limitedBudgetPlan(RouteProcessor.lowestPriceRoute());
            }
            if (routePerferences.getSelectedIndex() == 2) {
                plan = RouteProcessor.limitedBudgetPlan(RouteProcessor.leastDaysRoute());
            }
            if (routePerferences.getSelectedIndex() == 0) {
                plan = RouteProcessor.noChoiceRoute();
            }
            for (Attraction a : plan) {
                m1.addElement(a.toString());
                planAttractions = planAttractions + a.getName() + " ";
                planBudget = planBudget + a.getBudget();
                planDays = planDays + a.getDay();
                weather = weather + a.getName() + ":" + a.getWeather() + ".\n";
            }
            m2.addElement(planAttractions);
            m2.addElement("Total budget is: " + planBudget + "\n");
            m2.addElement("Total cost:" + planDays + " days.\n");
            m2.addElement(weather);
            Graphics g = jPanel1.getGraphics();
            for (int l = 0; l < plan.size() - 1; l++) {
               g.setColor(Color.yellow);
               g.drawLine(plan.get(l).getCoordinate().getX(), plan.get(l).getCoordinate().getY(), plan.get(l + 1).getCoordinate().getX(), plan.get(l + 1).getCoordinate().getY());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_generateButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        DefaultListModel m1 = (DefaultListModel) (jList1.getModel());
        m1.clear();
        DefaultListModel m2 = (DefaultListModel) (jList2.getModel());
        m2.clear();
        String planAttractions = "Route is:";
        Double planBudget = 0.0;
        int planDays = 0;
        String weather = "Weather will be:";
        int n = jList1.getSelectedIndex();
        plan.remove(n);
        for (Attraction a : plan) {
            m1.addElement(a.toString());
            planAttractions = planAttractions + a.getName() + " ";
            planBudget = planBudget + a.getBudget();
            planDays = planDays + a.getDay();
            weather = weather + a.getName() + ":" + a.getWeather() + ".\n";
        }
        m2.addElement(planAttractions);
        m2.addElement("Total budget is: " + planBudget + "\n");
        m2.addElement("Total cost:" + planDays + " days.\n");
        m2.addElement(weather);

    }//GEN-LAST:event_modifyButtonActionPerformed

    private void outputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputButtonActionPerformed
        TravelSystem.outputPlan(plan);
        JOptionPane.showMessageDialog(null, "Plan has been printed, please chech your document.");// TODO add your handling code here:
    }//GEN-LAST:event_outputButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox attractionsPerferences;
    private javax.swing.JTextField budgetText;
    private javax.swing.JTextField destinationText;
    private javax.swing.JButton generateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private static travelmagic.map.AttractionLabel attractionLabel;
    private static travelmagic.map.HotelLabel hotelLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton outputButton;
    private javax.swing.JMenu reservationMenu;
    private javax.swing.JComboBox routePerferences;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchText;
    private javax.swing.JTextField startLocationText;
    private javax.swing.JMenu travelingCautionsMenu;
    // End of variables declaration//GEN-END:variables

}
